### ISSUE TITLE
Documentation consistency fix

### ISSUE THREAD

**Issue by jackregnart** [tryshoppe/shoppe-stripe#1]
In this section;

https://github.com/tryshoppe/stripe#receiving-your-payment-token

When accessing the session for the order id, you write;

`@order = Shoppe::Order.find(session[:current_order_id])`

Please use;

`@order = Shoppe::Order.find(session[:order_id])`

As that's what you use in the shoppe documentation.

**Comment by deanperry** [comment]
Updated, thanks
