### ISSUE TITLE
Multiple card processing issue

### ISSUE THREAD

**Issue by andretanguy** [tryshoppe/shoppe-stripe#10]
It looks like there is an issue with some customers being double (triple and quadruple billed) when paying via stripe. So here is my diagnosis of the issue so far:

1. A customer adds products to their cart and checkout
2. They enter their card details into the stripe form and a stripe token is then generated
3. The user then decides to go back to the shop and add other products (after the stripe token has been created)
4. They then go through the checkout process again

Step 4 is where I believe the issue lies. A new token is created thus when the customer is asked to 'finalise their order', the card is being processed more than once.

**Comment by deanperry** [comment]
Hmm, I'll try and replicate this

**Comment by andretanguy** [comment]
Thanks.
