### ISSUE TITLE
cannot use with new shoppe 1.0

### ISSUE THREAD

**Issue by andretanguy** [tryshoppe/shoppe-stripe#3]
Bundler could not find compatible versions for gem "shoppe":
  In Gemfile:
    shoppe-stripe (>= 0) ruby depends on
      shoppe (~> 0.0.8) ruby

    shoppe (1.0.0)

**Comment by thangluu** [comment]
same problem with 1.0.3 
Bundler could not find compatible versions for gem "shoppe":
In Gemfile:
    shoppe-stripe (>= 0) ruby depends on
      shoppe (~> 0.0.8) ruby

    shoppe (1.0.3)

**Comment by deanperry** [comment]
The latest version of the shoppe-stripe (v1.2.2) should fix this issue
