### ISSUE TITLE
Tutorial: No stripe_token being passed.

### ISSUE THREAD

**Issue by vpetkar** [tryshoppe/shoppe-stripe#9]
I've followed the tutorial exactly, however no stripe_token is being passed and it is blank after post. I have installed the correct gems and verified the keys in Shoppe Settings. 

When trying to pay: 

```ruby
  def payment
    @order = Shoppe::Order.find(session[:order_id])
    if request.post?
      if @order.accept_stripe_token(params[:stripe_token])
        redirect_to checkout_confirmation_path
      else
        flash.now[:notice] = "Could not exchange Stripe token. Please try again."
      end
    end
  end
```
Specifically, 
`flash.now[:notice] = "Could not exchange Stripe token. Please try again." ` is being called.

The only thing I can think of is an error with how stripe.js is handled with Shoppe-Stripe or a problem with Stripe itself (perhaps a breaking update?). Stripe's account logs show no requests from shoppe though. I am not sure how to debug this...'

All code can be found on vpetkar/enactus-impress/impress_shop

**Comment by vpetkar** [comment]
Solution: The [tutorial](http://tryshoppe.com/docs/payment-gateways/stripe) is misleading and you must place the require statement in `app/assets/javascripts/application.js` and not only in `app/assets/application.js`.

**Comment by deanperry** [comment]
Fixed with https://github.com/tryshoppe/documentation/pull/11
